site_name: EShop Application Documentation
plugins:
- search
- mermaid2:
    arguments:
      securityLevel: sandbox
extra_css:
- css/extra_css.css
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.integrate
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
markdown_extensions:
- admonition
- pymdownx.details
nav:
- Home: index.md
- Catalog.API:
  - Catalog Api:
    - Catalog Creation: Catalog.API/CatalogApi/CatalogCreation.md
    - Catalog Deletion: Catalog.API/CatalogApi/CatalogDeletion.md
    - Catalog Retrieval: Catalog.API/CatalogApi/CatalogRetrieval.md
    - Catalog Update: Catalog.API/CatalogApi/CatalogUpdate.md
  - Extensions: Catalog.API/Extensions.md
  - Integration Event Handlers: Catalog.API/IntegrationEventHandlers.md
  - Models: Catalog.API/Models.md
- Ordering.API:
  - Orders Api:
    - Order Cancellation: Ordering.API/OrdersApi/OrderCancellation.md
    - Order Card Types Management: Ordering.API/OrdersApi/OrderCardTypesManagement.md
    - Order Creation: Ordering.API/OrdersApi/OrderCreation.md
    - Order Retrieval: Ordering.API/OrdersApi/OrderRetrieval.md
    - Order Shipping: Ordering.API/OrdersApi/OrderShipping.md
  - Commands: Ordering.API/Commands.md
  - Domain Event Handling: Ordering.API/DomainEventHandling.md
  - Extensions: Ordering.API/Extensions.md
  - Integration Event Handlers: Ordering.API/IntegrationEventHandlers.md
  - Models: Ordering.API/Models.md
  - Queries: Ordering.API/Queries.md
  - Validations: Ordering.API/Validations.md
- Ordering.Domain:
  - Aggregate: Ordering.Domain/Aggregate.md
  - Models: Ordering.Domain/Models.md
  - index: Ordering.Domain/index.md
- Ordering.Infrastructure:
  - Extensions: Ordering.Infrastructure/Extensions.md
  - Models: Ordering.Infrastructure/Models.md
  - index: Ordering.Infrastructure/index.md
- catalog api: catalog-api.md
- ordering api: ordering-api.md
